// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaYATzrmAhk-2x_1FdY3yBxmNe9_SIs6o',
    appId: '1:651246376734:web:00c938e493f1d4cad75b0f',
    messagingSenderId: '651246376734',
    projectId: 'fir-tutorial-6b6b1',
    authDomain: 'fir-tutorial-6b6b1.firebaseapp.com',
    storageBucket: 'fir-tutorial-6b6b1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYKhQ5uzcAAxyBWTjeLpuWPaESROU5ofk',
    appId: '1:651246376734:android:ad8b0b25b493781bd75b0f',
    messagingSenderId: '651246376734',
    projectId: 'fir-tutorial-6b6b1',
    storageBucket: 'fir-tutorial-6b6b1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDO2qJwM3k1Or1phzQmN4WWvPDujiq3Unc',
    appId: '1:651246376734:ios:dface3e7a2e836f1d75b0f',
    messagingSenderId: '651246376734',
    projectId: 'fir-tutorial-6b6b1',
    storageBucket: 'fir-tutorial-6b6b1.appspot.com',
    iosClientId: '651246376734-pmb8g72jkb23due9rvbmg2v17sl34e23.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseAuth',
  );
}
